//
//  WDRList.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class WDRListBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface WDRList : NSObject<NSCopying, NSSecureCoding>
@property (nonatomic, assign, readonly) double revision;
@property (nullable, nonatomic, copy, readonly) NSString * listType;
@property (nullable, nonatomic, copy, readonly) NSString * ownerType;
@property (nullable, nonatomic, copy, readonly) NSString * identifier;
@property (nullable, nonatomic, strong, readonly) NSArray * tasks;
@property (nullable, nonatomic, copy, readonly) NSString * ownerId;
@property (nullable, nonatomic, copy, readonly) NSString * title;
@property (nullable, nonatomic, copy, readonly) NSString * type;
@property (nonatomic, assign, readonly) BOOL public;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(WDRListBuilder *)builder;
- (instancetype)initWithBuilder:(WDRListBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(WDRListBuilder *builder))block;
- (BOOL)isEqualToList:(WDRList *)anObject;
- (instancetype)mergeWithModel:(WDRList *)modelObject;
- (instancetype)mergeWithModel:(WDRList *)modelObject initType:(PlankModelInitType)initType;
@end

@interface WDRListBuilder : NSObject
@property (nonatomic, assign, readwrite) double revision;
@property (nullable, nonatomic, copy, readwrite) NSString * listType;
@property (nullable, nonatomic, copy, readwrite) NSString * ownerType;
@property (nullable, nonatomic, copy, readwrite) NSString * identifier;
@property (nullable, nonatomic, strong, readwrite) NSArray * tasks;
@property (nullable, nonatomic, copy, readwrite) NSString * ownerId;
@property (nullable, nonatomic, copy, readwrite) NSString * title;
@property (nullable, nonatomic, copy, readwrite) NSString * type;
@property (nonatomic, assign, readwrite) BOOL public;
- (instancetype)initWithModel:(WDRList *)modelObject;
- (WDRList *)build;
- (void)mergeWithModel:(WDRList *)modelObject;
@end

NS_ASSUME_NONNULL_END
