//
//  WDRTask.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class WDRTaskBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface WDRTask : NSObject<NSCopying, NSSecureCoding>
@property (nullable, nonatomic, copy, readonly) NSString * revision;
@property (nullable, nonatomic, strong, readonly) NSDate * dueDate;
@property (nonatomic, assign, readonly) BOOL starred;
@property (nullable, nonatomic, copy, readonly) NSString * createdById;
@property (nullable, nonatomic, copy, readonly) NSString * identifier;
@property (nonatomic, assign, readonly) BOOL completed;
@property (nullable, nonatomic, strong, readonly) NSDate * createdAt;
@property (nullable, nonatomic, copy, readonly) NSString * title;
@property (nullable, nonatomic, copy, readonly) NSString * type;
@property (nullable, nonatomic, copy, readonly) NSString * createdByRequestId;
@property (nullable, nonatomic, copy, readonly) NSString * listId;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(WDRTaskBuilder *)builder;
- (instancetype)initWithBuilder:(WDRTaskBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(WDRTaskBuilder *builder))block;
- (BOOL)isEqualToTask:(WDRTask *)anObject;
- (instancetype)mergeWithModel:(WDRTask *)modelObject;
- (instancetype)mergeWithModel:(WDRTask *)modelObject initType:(PlankModelInitType)initType;
@end

@interface WDRTaskBuilder : NSObject
@property (nullable, nonatomic, copy, readwrite) NSString * revision;
@property (nullable, nonatomic, strong, readwrite) NSDate * dueDate;
@property (nonatomic, assign, readwrite) BOOL starred;
@property (nullable, nonatomic, copy, readwrite) NSString * createdById;
@property (nullable, nonatomic, copy, readwrite) NSString * identifier;
@property (nonatomic, assign, readwrite) BOOL completed;
@property (nullable, nonatomic, strong, readwrite) NSDate * createdAt;
@property (nullable, nonatomic, copy, readwrite) NSString * title;
@property (nullable, nonatomic, copy, readwrite) NSString * type;
@property (nullable, nonatomic, copy, readwrite) NSString * createdByRequestId;
@property (nullable, nonatomic, copy, readwrite) NSString * listId;
- (instancetype)initWithModel:(WDRTask *)modelObject;
- (WDRTask *)build;
- (void)mergeWithModel:(WDRTask *)modelObject;
@end

NS_ASSUME_NONNULL_END
